### ISSUE TITLE
Plot not showing

### ISSUE THREAD

**Issue by daleher** [chardiegit/python-intermediate-inflammation#4]
Following error appears after running the tool and trying to get a plot

/mnt/c/Users/danleon/Intermediate_Software_Development/Issues_Exercise/python-intermediate-inflammation/inflammation/views.py:25: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

**Comment by chardiegit** [comment]
15 minutes

**Comment by lubro-crypto** [comment]
Added line in Readme.
