### ISSUE TITLE
Extraneous file `h origin v1.0.0`

### ISSUE THREAD

**Issue by bielsnohr** [chardiegit/python-intermediate-inflammation#6]
There is what appears to be a spurious file at the top of the directory, called [h origin v1.0.0](https://github.com/chardiegit/python-intermediate-inflammation/blob/main/h%20origin%20v1.0.0). It should be verified whether this file is needed for some purpose.

**Comment by chardiegit** [comment]
5 minutes to resolve - delete file

**Comment by lubro-crypto** [comment]
Fixed by 0a96474588b36b1067a9a77e653f9a08326af51a
